FROM php:8.2-fpm

RUN apt-get update && apt-get install -y --no-install-recommends \
    zlib1g-dev \
    libxml2-dev \
    libpng-dev \
    libzip-dev \
    vim curl apt-transport-https apt-utils \
    build-essential locales sudo \
    && docker-php-ext-install \
    pdo_mysql \
    zip \
    opcache \
    gd \
    intl
# COPY build/php/opcache.ini /usr/local/etc/php/conf.d/
# COPY build/php/custom.ini /usr/local/etc/php/conf.d/
WORKDIR /var/www/html
COPY --chown=www-data:www-data ../../project /var/www/html

ARG DATABASE_URL
ARG APP_ENV
ENV APP_ENV=${APP_ENV}
ENV DATABASE_URL=${DATABASE_URL}
ENV COMPOSER_ALLOW_SUPERUSER=1

RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer
RUN composer install --no-scripts --no-interaction --optimize-autoloader
# RUN wget --no-check-certificate https://phar.phpunit.de/phpunit-6.5.3.phar && \
#     mv phpunit*.phar phpunit.phar && \
#     chmod +x phpunit.phar && \
#     mv phpunit.phar /usr/local/bin/phpunit
RUN usermod -u 1000 www-data
RUN usermod -a -G www-data root
RUN mkdir -p /var/www
RUN chown -R www-data:www-data /var/www
RUN mkdir -p /var/www/.composer
RUN chown -R www-data:www-data /var/www/.composer