services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../project/public/assets:/var/www/html/public/assets
      - ../project/public/uploads:/var/www/html/public/uploads
    ports:
      - 8000:80
    networks:
      - symfony

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - symfony

  php:
    build:
      context: ..
      dockerfile: docker/php/Dockerfile
    # volumes:
    #   - ../project:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://symfony:symfony@127.0.0.1:3306/symfony
    networks:
      - symfony
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
