version: '3'
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_DEBUG=1
    networks:
      - symfony

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html:cached
    ports:
      - 8000:80
    networks:
      - symfony

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - ./db/db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - symfony

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - symfony

networks:
  symfony:
    driver: bridge
